name: tunza
version: 0.0.1
description: A zero project
main: lib/main.dart
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  zero:
    git:
      url: https://github.com/bryanbill/zero
      ref: dev
  
  postgres: ^2.6.1
  dart_jsonwebtoken: ^2.7.1
  crypto: ^3.0.1
  gcloud: ^0.8.8
  
dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.0
