name: tunza
version: 0.0.1
description: A zero project
main: lib/main.dart
publish_to: none
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  zero:
    path: ../

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.0
